package thsCrack;

public class MiddlewareProxy {
    private static final String APPNAME = "appname";
    private static final String APP_VERSION = "appver";
    private static final String DEVICE = "device";
    private static final String DEVICE_ID = "deviceid";
    public static final String DEVICE_IMEI = "imei";
    public static final String DEVICE_IMSI = "imsi";
    public static final String ENCODE_TYPE_GBK = "GBK";
    public static final String ENCODE_TYPE_UTF8 = "UTF-8";
    private static final String FOR = "for";
    public static final String HK_MARKET_ID_C = "178";
    public static final String HK_MARKET_ID_M = "177";
    private static final String INDEX_CQ = "cq";
    public static final int INDEX_DDE = 0;
    private static final String INDEX_DKQS = "dkqs";
    public static final int INDEX_FIVE = 5;
    private static final String INDEX_FSMMD = "fsmmd";
    public static final int INDEX_HQ = 3;
    private static final String INDEX_JYCCCBX = "jycccbx";
    private static final String INDEX_KLINE_JUNXIAN = "kljx";
    private static final String INDEX_LSMMD = "lsmmd";
    private static final int INDEX_OPEN = 1;
    private static final String INDEX_QFQ = "qfq";
    private static final String INDEX_QK = "qk";
    public static final int INDEX_ZIXUAN = 2;
    private static final String INNER_VERSION = "innerver";
    private static final String INTERNALVERSION = "internalVersion";
    private static final String LUNGUDEVICEID = "lungudeviceid";
    private static final String MODEL = "model";
    private static final String NET = "net";
    public static final int NEWS_INVALID = 0;
    public static final int NEWS_READED = 2;
    public static final int NEWS_UNREAD = 1;
    private static final int NEWUSER = 1;
    private static final String OSVERSION = "osversion";
    public static final long OUT_TIME_REQUEST = 20000;
    private static final String PLATFORM = "platform";
    public static final String PORT_PRE_RELEASE = "9530";
    public static final String PORT_RELEASE = "9528";
    public static final String PORT_TEST = "9628";
    private static final String POSTSCANID = "postscanid";
    public static final boolean RN_DEV_MODE = false;
    private static final String SDKN = "sdkn";
    private static final String SDK_NUM = "sdknum";
    private static final String SERVERINFO = "serverinfo";
    private static final String SERVER_ADDRESS = "serverAddr";
    private static final String SIGN_AND = "&";
    private static final String SIGN_EQAL = "=";
    private static final String SOURCEID = "sourceid";
    public static final int STANDARD_LENGTH = 32;
    private static final String TAG = "MiddlewareProxy";
    public static final int TIME_OUT_DEFAULT = 0;
    private static final String TYPE = "type";
    private static final String USERID = "userid";
    private static final String USERNAME = "username";
    private static String encryptUDID;
    private static String hdInfo;
//    private static ewx mAMConnectionManager;
//    private static anx mCloudBuyInfo;
//    private static fss mConfigManager;
//    private static evu mDatabaseService;
//    private static eod mFunctionManager;
//    private static exm mHangqingConfigManager;
//    private static eun mMobileDataCache;
//    private static epq mNodeManager;
//    private static eof mPageJumpManager;
//    private static eoj mRuntimeDataManager;
//    private static eob mScreenManager;
//    private static evx mSelfStockManager;
//    private static euo mStockListCacheManager;
//    private static cpo mUiControllerFactory;
//    private static cpp mUiManager;
//    private static hlp mWearConnectionManager;
//    private static hlr mWearableApiHelp;
    private static boolean sUdidReadyToBind = false;
    private static boolean sUdidReadyRoBindDebug = false;
    private static int selectTabIndex = 0;
    private static int lastTabIndex = 0;
    private static int serverType = -1;
    private static long periodForInitRes = 0;
//    private static final List<ezx> activityLifeCycleListeners = new ArrayList();

}
